name: Auto Git Push Every 1 Minute

on:
  schedule:
    - cron: '*/1 * * * *'  # every 1 minute
  workflow_dispatch:       # allow manual trigger for testing

jobs:
  auto-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config --global user.name "Sudip Laudari"
        git config --global user.email "sudiplaudari@gmail.com"

    - name: Make dummy change (timestamp)
      run: |
        echo "Last update: $(date -u)" > .autopush-log.txt

    - name: Commit and push changes
      run: |
        git add .autopush-log.txt
        git commit -m "Testing CI/CD process" || echo "No changes to commit"
        git pull --rebase origin main
        git push origin HEAD
