name: Auto Git Push Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:       # allow manual trigger for testing

jobs:
  auto-push:
    runs-on: ubuntu-latest
    concurrency:
      group: auto-push
      cancel-in-progress: true  # ensure only one run at a time

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # ensures full history for pull --rebase

    - name: Configure Git
      run: |
        git config --global user.name "Sudip Laudari"
        git config --global user.email "sudiplaudari@gmail.com"

    - name: Pull latest changes with conflict resolution
      run: |
        git pull --rebase origin main || (
          echo "Rebase conflict detected, resolving by keeping latest .autopush-log.txt"
          git rebase --abort
          git fetch origin main
          git reset --hard origin/main
          echo "Last update: $(date -u)" > .autopush-log.txt
          git add .autopush-log.txt
          git commit -m "🔄 Resolved conflict and updated: $(date -u)"
        )

    - name: Update timestamp in .autopush-log.txt
      run: |
        echo "Last update: $(date -u)" > .autopush-log.txt

    - name: Commit and push changes
      run: |
        git add .autopush-log.txt
        git diff --cached --quiet && echo "No changes to commit" || (git commit -m "🔄 Scheduled auto update: $(date -u)" && git push origin main)
