name: Auto Git Push Every 1 Minute

on:
  schedule:
    - cron: '*/1 * * * *'  # every 1 minute
  workflow_dispatch:

jobs:
  auto-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensure full history

    - name: Set up Git config
      run: |
        git config --global user.name "Sudip Laudari"
        git config --global user.email "sudiplaudari@gmail.com"

    - name: Set working branch
      run: |
        git checkout main

    - name: Make dummy change
      run: |
        echo "Last update: $(date -u)" > .autopush-log.txt

    - name: Commit and push changes
      run: |
        git add .autopush-log.txt
        git commit -m "🔄 Scheduled auto update: $(date -u)" || echo "No changes to commit"
        git pull origin main --rebase
        git push origin main
